#! /usr/bin/env python
# encoding: utf-8

VERSION="1.0"

top='.'
out='build'

def options(opt):
    opt.load('compiler_c')

def configure(conf):
    conf.env.CXXFLAGS+=['-Wall']
    conf.load('compiler_c')
    conf.env.VERSION=VERSION

    conf.write_config_header('config.h')
    conf.define('HAVE_CONFIG_H', 1)

def build(bld):
    bld.stlib(
        source=['trace.c', 'tool.c'],
        includes=['.', 'build'],
        target='trace',
        use=['PTHREAD'],
        vnum=bld.env.VERSION,
        )
