#! /usr/bin/env python
# encoding: utf-8

APPNAME='final'
VERSION="0.0.1"

top='.'
out='build'

def options(opt):
    opt.load('compiler_c')

def configure(conf):
    conf.env.CXXFLAGS+=['-Wall']
    conf.load('compiler_c')
    
    conf.recurse('libtrace')

    conf.env.VERSION=VERSION
    conf.env.INCLUDES += ['libtrace']

def build(bld):
    bld.recurse('libtrace')
    bld.program(
        source=['final.c',
                ],
        target=APPNAME,
        use=['trace'],
        vnum=bld.env.VERSION,
        )
